# Generated by Django 5.2.1 on 2025-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Poultry", "0002_rename_amount_taken_feed_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chickenbatch",
            name="weight",
            field=models.FloatField(),
        ),
    ]
